dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0"

dotenv: .env
networks:
  default: development
  my-ganache:
    verify: False
  development:
    verify: False
  rinkeby:
    verify: True
  kovan:
    verify: True
  mainnet-fork:
    verify: False
wallets:
  private_key: ${PRIVATE_KEY}
