dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0"

dotenv: .env
networks:
  default: development
  development:
    verify: True
    recipient: "0x35Af6B31a61eC9F030849a3953394A69a1f9f9eC"
  rinkeby:
    verify: True
  kovan:
    verify: True
  mainnet-fork:
    verify: False
wallets:
  private_key: ${PRIVATE_KEY}
